/**
 * styles.ts — the stylesheets as STRINGS, for a host that injects a `<style>`
 * element itself (the aiui widget convention: a widget's styles travel as a
 * string the host concatenates, so a library that embeds the inspector needs
 * no CSS import of its own and no bundler contract for one). The CSS files
 * behind the `./style.css` and `./themes/*.css` subpaths are the source of
 * truth; `styles.generated.ts` is their text, regenerated by
 * `pnpm gen:styles` and guarded by a test.
 */
import { AIUI, BASE, TERMINAL } from "./styles.generated.ts";

export const INSPECTOR_STYLES: Readonly<{
  /** The neutral base stylesheet (`./style.css`). */
  base: string;
  /** The optional themes, keyed by the `data-prompt-theme` value they answer to. */
  themes: Readonly<{ aiui: string; terminal: string }>;
}> = Object.freeze({ base: BASE, themes: Object.freeze({ aiui: AIUI, terminal: TERMINAL }) });
