/**
 * palette.ts — one colour per project, everywhere (playbook layer 1).
 *
 * ## Why this exists
 *
 * Each chart used to derive its own colour scale from whatever rows it happened
 * to be showing. Two consequences, both wrong: `pdum_aiui` was grey in the
 * scatter and grey-ish in spend-by-day only by luck, and clicking a legend
 * entry to isolate one project **recoloured it** — the filtered data had one
 * category, so it got the scheme's first colour. A colour that changes when you
 * select it is not an identity.
 *
 * So the domain is fixed here, from the whole corpus, and every chart is handed
 * the same `(domain, range)` pair. A project's colour is now a property of the
 * project.
 *
 * ## The palette, measured
 *
 * Generated by searching OKLCH for twelve colours that clear 3:1 against the
 * panel surface (#1a1d23) while maximising the minimum pairwise difference —
 * then re-scored under simulated colour-vision deficiency, which changed the
 * answer:
 *
 * | palette | normal ΔE00 | deutan ΔE00 | contrast |
 * | --- | ---: | ---: | ---: |
 * | Tableau-12 | 2.6 | — | 3.71:1 |
 * | max-separation hue spread | 18.6 | **0.5** | 4.76:1 |
 * | **this one** (lightness spread) | **13.3** | **9.0** | **4.05:1** |
 *
 * The middle row is the trap: it looks best and is unusable, because twelve
 * evenly-spaced hues collapse onto one axis under deuteranopia — its worst pair
 * becomes indistinguishable (ΔE 0.5). Spreading *lightness* as well as hue
 * costs 5.3 ΔE of normal-vision headroom (13.3 is still far above the ~10 that
 * reads as clearly different) and buys an 18× improvement in the worst case
 * that matters. Full profile: protan 5.1, deutan 9.0, tritan 6.6.
 *
 * **Twelve categories cannot be made CVD-safe** — none of protan/deutan/tritan
 * clears the ~12 that would be comfortable, and no palette of this size will.
 * That is a real limit of encoding twelve things in colour, not a palette bug,
 * and the honest remedy is to show fewer at once. Which is what the project
 * filter is for.
 */

/**
 * The twelve colours, **reordered so consecutive entries are far apart**.
 *
 * Assignment is by sorted project name, so a project keeps its colour as the
 * corpus grows. But sorted names are not independent: `pdum_aiui`, `pdum_dsl`
 * and `pdum_rfb` sort together *because they are related*, which makes them
 * exactly the set you most need to tell apart — and in generation order they
 * landed on three neighbouring hues (green, teal, cyan).
 *
 * Walking the generated ring in steps of 5 (coprime with 12, so still a
 * permutation) fixes that without changing the colours themselves:
 *
 * | adjacent-name ΔE00 | generation order | step-5 order |
 * | --- | ---: | ---: |
 * | normal vision | 13.3 | **46.9** |
 * | deuteranopia | 9.0 | **12.6** |
 *
 * For the three `pdum_*` projects specifically, pairwise normal-vision
 * separation goes from (17.0, 13.3, 30.1) to (46.9, 58.2, 30.8).
 */
export const PROJECT_COLORS = [
  "#0083c4",
  "#ffa18e",
  "#21dac0",
  "#b463ad",
  "#c6df70",
  "#7893ef",
  "#ce7925",
  "#4af7ff",
  "#ea7da1",
  "#53b56d",
  "#c7a3ff",
  "#d3ac31",
] as const;

/** Beyond the palette's length, colours repeat. Said out loud rather than hidden. */
export const paletteSize = PROJECT_COLORS.length;

/**
 * The `(domain, range)` pair every project-coloured chart should use.
 *
 * Sorted so the mapping is a pure function of the project set: same corpus,
 * same colours, in any chart and on any reload.
 */
export function projectScale(projects: readonly string[]): {
  domain: string[];
  range: string[];
} {
  const domain = [...new Set(projects)].sort();
  return {
    domain,
    range: domain.map((_, i) => PROJECT_COLORS[i % PROJECT_COLORS.length]),
  };
}

/** One project's colour, for a chip or a swatch outside a chart. */
export function projectColor(projects: readonly string[], project: string): string {
  const { domain, range } = projectScale(projects);
  const i = domain.indexOf(project);
  return i < 0 ? "var(--cco-fg-dim)" : range[i];
}
