/**
 * Render-audit harness (uncommitted working tool).
 *
 * Drives every item→text render path in the lowering pipeline's render.ts, plus
 * the channel's context preamble and the MCP self-description strings, with
 * representative inputs, and emits the ACTUAL rendered output for each case as
 * one markdown document — so the audit reviews real outputs side by side
 * instead of spelunking the code.
 *
 * The annotate-iterate loop:
 *  - output goes to <repo>/audit.local/render-audit.md (gitignored via *.local)
 *  - every case ends with a `**Comments:**` block; the owner writes decisions
 *    there in place, and the agent reads them back to drive code changes
 *  - each run first backs up the existing file to render-audit.v<N>.md, so an
 *    annotated round survives regeneration and `diff v<N> render-audit.md`
 *    shows exactly what a code change did to the outputs
 *
 * Run: pnpm exec tsx render-audit.mts [output.md]   (from this package dir)
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type ComposedItem,
  type ComposeOptions,
  renderPrompt,
} from "@habemus-papadum/aiui-lowering-pipeline";
import {
  promptContextSections,
  selectionSections,
  TRANSCRIPTION_NOTE,
  wrapWithContextParts,
} from "./src/prompt-context";
import { INSTRUCTIONS } from "./src/server";

/**
 * `--docs` mode: emit the settled reference (no Comments blocks, a
 * documentation intro) to docs/guide/prompt-rendering.md instead of the
 * audit.local working pair.
 */
const DOCS_MODE = process.argv.includes("--docs");

const CWD = "/repo/app";
const out: string[] = [];
const md = (s: string): void => {
  out.push(s);
};

const NO_COMMENT = "_none yet_";
/** The owner's annotation slot — one per case; absent from the docs build. */
const comments = (): void => {
  if (!DOCS_MODE) {
    md(`**Comments:**\n\n${NO_COMMENT}\n`);
  }
};

let caseNo = 0;

/** Drop fields the renderer never reads from the Input displays (noted in the intro). */
const jsonReplacer = (key: string, value: unknown): unknown =>
  key === "rect" || key === "segment" ? undefined : value;

/** Render `items` through the real pass 5 and emit the case as Input → Rendered. */
function show(
  title: string,
  note: string,
  items: ComposedItem[],
  options: ComposeOptions = { cwd: CWD },
): void {
  caseNo += 1;
  const composed = renderPrompt(items, [], "replace", options);
  md(`### ${caseNo}. ${title}\n`);
  if (note) md(`${note}\n`);
  const value = items.length === 1 ? items[0] : items;
  md("Input:\n");
  md("````json\n" + JSON.stringify(value, jsonReplacer, 2) + "\n````\n");
  md("Rendered:\n");
  md("````text\n" + composed.prompt + "\n````\n");
  comments();
}

/** A transcript run (`kind: "text"`) — used ONLY in section G, the interleave case. */
const text = (t: string): ComposedItem => ({ kind: "text", text: t, segment: 1 });

const SHOT_PATH = `${CWD}/.aiui-cache/traces/t1/shot_1.png`;

// ─────────────────────────────────────────────────────────────────────────────
md(
  DOCS_MODE
    ? "# Prompt rendering reference\n"
    : "# Render audit — every item→text path, actual outputs\n",
);
md(
  (DOCS_MODE
    ? "How the intent lowering renders each captured item into the prompt an agent reads — " +
      "every render path with its actual output, generated from the real renderer. "
    : "Generated by `packages/aiui-claude-channel/render-audit.mts` against the worktree's real " +
      "`renderPrompt`. ") +
    `All cases use \`cwd: ${CWD}\` unless noted, so relativization is visible. ` +
    "Each case shows the RAW input value (the `ComposedItem` fed to the renderer, as JSON — " +
    "`rect` fields omitted, the renderer never reads them) and the exact rendered text. Each " +
    "section opens with the input schema once; cases only vary the values. Only section G mixes " +
    'in `kind: "text"` transcript runs — everywhere else the input is purely the item under audit.\n',
);
md(
  DOCS_MODE
    ? "> **Generated file — do not edit.** Rebuild with " +
        "`pnpm -C packages/aiui-claude-channel render-audit --docs` after changing the renderer. " +
        "The same script (without `--docs`) produces the annotatable render-audit working pair in " +
        "`audit.local/` — the mechanism for iterating on these renderings.\n"
    : "**How to annotate:** work in `render-audit.markup.md` (this file's identical twin) — " +
        "*meta-commentary* goes in a case's `**Comments:**` block (replacing “_none yet_”); " +
        "*concrete wording changes* you make by directly editing the rendered output text in place. " +
        "`render-audit.md` stays pristine; the agent diffs the two to pick up both kinds of feedback. " +
        "Each regeneration backs the previous round up as a numbered pair " +
        "(`render-audit.v<N>.md` / `render-audit.markup.v<N>.md`).\n",
);

md(
  "## A. Screenshots — the ONE form (bracket line + `<screenshot-metadata>` when elements were located)\n",
);
md('Input schema (`ComposedItem`, `kind: "shot"` — the fields the renderer reads):\n');
md(
  "````ts\n" +
    `{
  kind: "shot";
  marker: string;       // stream identity (shot_N)
  path?: string;        // saved image on disk; absent → capture failed
  viewport?: boolean;   // whole-viewport shot (no element metadata by design)
  origin?: "paste";     // clipboard image, not the screen
  share?: {             // present when a video share's sampler took the frame
    ordinal: number; mode: "smart" | "continuous"; offsetMs: number };
  components?: Array<{  // elements located under the capture rect
    component: string;
    source?: string;                 // file:line:col; "unknown" → attribute dropped
    containment?: "within";          // enclosing anchor — context, not framing
    cells?: Array<{ name: string; source?: string }> }>;
}` +
    "\n````\n",
);

show("Viewport shot (bare bracket line, no element info by design)", "Trigger: `viewport: true`.", [
  { kind: "shot", marker: "shot_1", path: SHOT_PATH, viewport: true },
]);

show("Region shot, no located components", "Trigger: empty `components`. Bracket line only.", [
  { kind: "shot", marker: "shot_1", path: SHOT_PATH, components: [] },
]);

show(
  "Region shot with elements and cells (the rich block)",
  'Trigger: components with sources and cells; one `containment: "within"` anchor; one `source: "unknown"` (dropped attr); one cell without a source.',
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Legend",
          source: `${CWD}/src/Legend.tsx:30:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [{ name: "colorScale", source: `${CWD}/src/Legend.tsx:41:8` }, { name: "ticks" }],
        },
        {
          component: "Plot",
          source: "unknown",
          rect: { x: 0, y: 0, w: 10, h: 10 },
        },
        {
          component: "Panel",
          source: `${CWD}/src/Panel.tsx:5:1`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          containment: "within",
        },
      ],
    },
  ],
);

show(
  "Cell overflow (>4 cells → `cells-omitted`)",
  "Trigger: 6 cells on one element; the first 4 list, 2 collapse.",
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Dashboard",
          source: `${CWD}/src/Dash.tsx:1:1`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [1, 2, 3, 4, 5, 6].map((n) => ({ name: `cell${n}` })),
        },
      ],
    },
  ],
);

show(
  "Element overflow (>8 components → `elements-omitted`)",
  "Trigger: 10 components; document order keeps the first 8.",
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: Array.from({ length: 10 }, (_, i) => ({
        component: `Widget${i + 1}`,
        source: `${CWD}/src/W${i + 1}.tsx:1:1`,
        rect: { x: 0, y: 0, w: 10, h: 10 },
      })),
    },
  ],
);

show(
  "Missing image (capture denied/unavailable)",
  "Trigger: no `path`. The marker keeps the reference alive.",
  [{ kind: "shot", marker: "shot_2", components: [] }],
);

show(
  "Pasted image (clipboard, not screen)",
  'Trigger: `origin: "paste"` — its own tag so the model can\'t mistake clipboard for screen.',
  [{ kind: "shot", marker: "shot_1", path: SHOT_PATH, origin: "paste", components: [] }],
);

show("Video-share frame, smart mode (captured on change)", 'Trigger: `share.mode: "smart"`.', [
  {
    kind: "shot",
    marker: "shot_1",
    path: SHOT_PATH,
    share: { ordinal: 1, mode: "smart", offsetMs: 0 },
    components: [],
  },
]);

show(
  "Video-share frame, continuous mode (capture time rides with the path)",
  'Trigger: `share.mode: "continuous"`, offset 12340ms.',
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      share: { ordinal: 1, mode: "continuous", offsetMs: 12340 },
      components: [],
    },
  ],
);

show(
  "Path outside cwd stays absolute; XML escaping in names",
  'Trigger: shot path outside cwd; a component named `A<B> & "C"`.',
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: "/elsewhere/traces/shot_9.png",
      components: [
        {
          component: 'A<B> & "C"',
          source: `${CWD}/src/AB.tsx:2:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
        },
      ],
    },
  ],
);

md("## C. Code selections\n");
md('Input schema (`ComposedItem`, `kind: "code-selection"`):\n');
md(
  "````ts\n" +
    `{
  kind: "code-selection";
  marker?: string;     // stream identity (code_N)
  text: string;        // the selected code, verbatim
  sourceLoc?: string;  // file:line:col or file:startLine-endLine; absent → MISSING_LOCATION
  lines?: number;      // line count (derived from text when absent)
  url?: string;        // the contributing view's location.href → <tab> record
}` +
    "\n````\n",
);

show("Short code selection with locator (inlined)", "Trigger: ≤240 chars.", [
  {
    kind: "code-selection",
    marker: "code_1",
    text: "const x = 1;",
    sourceLoc: `${CWD}/src/a.ts:5:1`,
    lines: 1,
  },
]);

show("Short code selection, no locator", "Trigger: `sourceLoc` absent → `MISSING_LOCATION`.", [
  { kind: "code-selection", marker: "code_1", text: "let y = 2;" },
]);

show(
  "Short code selection with a contributing view's tab",
  "Trigger: the event carried `url` → the canonical `<tab>` record in metadata.",
  [
    {
      kind: "code-selection",
      marker: "code_1",
      text: "const x = 1;",
      sourceLoc: `${CWD}/src/a.ts:5:1`,
      url: "http://localhost:5173/reader",
      lines: 1,
    },
  ],
);

show("Long code selection (fenced block with line count)", "Trigger: >240 chars.", [
  {
    kind: "code-selection",
    marker: "code_1",
    text: Array.from(
      { length: 8 },
      (_, i) => `export function helper${i}(input: number): number { return input * ${i}; }`,
    ).join("\n"),
    sourceLoc: `${CWD}/src/helpers.ts:1-8`,
    lines: 8,
  },
]);

show(
  "Very long code selection (elided past 50 lines)",
  "Trigger: >50 lines → first 50 + an elision count inside the fence.",
  [
    {
      kind: "code-selection",
      marker: "code_1",
      text: Array.from({ length: 60 }, (_, i) => `const row${i + 1} = compute(${i + 1});`).join(
        "\n",
      ),
      sourceLoc: `${CWD}/src/table.ts:1-60`,
      lines: 60,
    },
  ],
);

md("## D. App (on-screen) selections\n");
md('Input schema (`ComposedItem`, `kind: "app-selection"`):\n');
md(
  "````ts\n" +
    `{
  kind: "app-selection";
  marker?: string;     // stream identity (sel_N)
  text: string;        // the selected page text
  sourceLoc?: string;  // data-source-loc of the selection's start element
  cell?: string;       // producing dataflow cell (data-cell)
  cellLoc?: string;    // that cell's definition site (file:line)
  tex?: string;        // TeX source when the selection is rendered mathematics
  url?: string;        // the page's location.href → <tab> record
}` +
    "\n````\n",
);

show("Short app selection, no attribution", "", [
  { kind: "app-selection", marker: "sel_1", text: "42.7" },
]);

show(
  "Short app selection, full attribution (metadata block with cell + tab)",
  "Trigger: sourceLoc + cell + cellLoc + the page url.",
  [
    {
      kind: "app-selection",
      marker: "sel_1",
      text: "42.7",
      sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
      cell: "meanValue",
      cellLoc: `${CWD}/src/model.ts:33`,
      url: "http://localhost:5173/sim?run=3",
    },
  ],
);

show("App selection of rendered mathematics (TeX attribution)", "", [
  {
    kind: "app-selection",
    marker: "sel_2",
    text: "∂u/∂t = D ∂²u/∂x²",
    sourceLoc: `${CWD}/src/Equation.tsx:8:2`,
    tex: "\\frac{\\partial u}{\\partial t} = D \\frac{\\partial^2 u}{\\partial x^2}",
  },
]);

show("Long app selection (fenced)", "Trigger: >240 chars of page text.", [
  {
    kind: "app-selection",
    marker: "sel_1",
    text: "The diffusion simulation shows temperature spreading through the rod over time. ".repeat(
      4,
    ),
    sourceLoc: `${CWD}/src/Explainer.tsx:3:1`,
    cell: "narrative",
  },
]);

md("## E. Boundaries (the current-tab model)\n");
md(
  'Input schema (`ComposedItem`, `kind: "navigation" | "tab-switch"`, and the canonical `TabRecord`):\n',
);
md(
  "````ts\n" +
    `{
  kind: "navigation" | "tab-switch";  // same tab changing page vs a different tab
  from: string;      // location.href before the boundary
  to: string;        // location.href after
  fromTab?: number;  // tab-switch only: the driver's handle for the tab left
  toTab?: number;    // tab-switch only: the driver's handle for the tab entered
  tab?: TabRecord;   // the DESTINATION tab's full record, when the client gathered one
}

// TabRecord — ONE shape wherever a tab is described (preamble, boundaries,
// selection metadata); renders as <tab …/> with only the known fields:
{
  url: string;           // full location.href — the list_pages matching key
  title?: string;        // document.title
  aiui?: boolean;        // page carries aiui instrumentation → aiui-app="true"
  sourceRoot?: string;   // the app's source root, when aiui
  chromeTabId?: number; windowId?: number; tabIndex?: number;  // extension ids
  targetId?: string;     // CDP Target.TargetID → cdp-target-id
  driverTab?: number;    // the plain-page host's CDP driver handle
}` +
    "\n````\n",
);

show(
  "Navigation (same tab), URL only",
  "The prior page needs no restating — the agent tracks the current tab.",
  [
    {
      kind: "navigation",
      from: "https://app.test/dashboard?tab=1",
      to: "https://app.test/detail#sec",
    },
  ],
);

show(
  "Navigation with a full destination tab record",
  "Trigger: the event carried `tab` — as much debug/correlation info as the client had.",
  [
    {
      kind: "navigation",
      from: "https://app.test/dashboard?tab=1",
      to: "http://localhost:5173/sim",
      tab: {
        url: "http://localhost:5173/sim",
        title: "Spectra — dev",
        aiui: true,
        chromeTabId: 712,
        windowId: 3,
        targetId: "F00D",
      },
    },
  ],
);

show(
  "Navigation with unparseable URLs",
  "Trigger: strings `new URL` rejects → raw string; empty → `?`.",
  [{ kind: "navigation", from: "not a url", to: "" }],
);

show(
  "Tab switch (no full record — the driver handle still yields a minimal <tab>)",
  "Trigger: `toTab` present, `tab` absent.",
  [
    {
      kind: "tab-switch",
      from: "https://app.test/a",
      to: "https://docs.test/api/ref",
      fromTab: 1,
      toTab: 2,
    },
  ],
);

md("## F. Corrections (note policy)\n");
md(
  "Input schema (a correction entry, alongside the transcript items):\n" +
    "````ts\n" +
    `{ original: string; instruction: string; applied: boolean }
// policy "note" + applied: false → appended parenthetical` +
    "\n````\n",
);

{
  caseNo += 1;
  const transcriptItems = [text("make the plot tall her")];
  const correction = { original: "tall her", instruction: "taller", applied: false };
  const composed = renderPrompt(transcriptItems, [correction], "note", { cwd: CWD });
  md(`### ${caseNo}. Unapplied correction under \`policy: "note"\`\n`);
  md("Trigger: a correction the patcher could not apply → appended parenthetical.\n");
  md("Input:\n");
  md(
    "````json\n" +
      JSON.stringify({ items: transcriptItems, corrections: [correction] }, jsonReplacer, 2) +
      "\n````\n",
  );
  md("Rendered:\n");
  md("````text\n" + composed.prompt + "\n````\n");
  comments();
}

md("## G. A full interleaved turn (joins, trims, blank-line separation)\n");

show(
  "Transcript runs · rich shot · selection · navigation · viewport shot",
  'The `kind: "text"` items are TRANSCRIPT RUNS (the user\'s spoken words) — this case audits the ' +
    "seams between them and the blocks: single-space joins, the multi-line block's surrounding " +
    "newlines (note the trailing space before each block's leading newline), leading/trailing trim.",
  [
    text("make this legend"),
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Legend",
          source: `${CWD}/src/Legend.tsx:30:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [{ name: "colorScale" }],
        },
      ],
    },
    text("wider, and align it with"),
    {
      kind: "app-selection",
      marker: "sel_1",
      text: "Mean: 42.7",
      sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
    },
    { kind: "navigation", from: "https://app.test/a", to: "https://app.test/b" },
    text("then check the whole page"),
    {
      kind: "shot",
      marker: "shot_2",
      path: `${CWD}/.aiui-cache/traces/t1/shot_2.png`,
      viewport: true,
    },
  ],
);

md("## H. The context preamble (channel, `prompt-context.ts`)\n");

{
  const fullHello = {
    tab: {
      title: "Spectra — dev",
      url: "http://localhost:5173/",
      chromeTabId: 712,
      windowId: 3,
      tabIndex: 0,
      targetId: "F00D",
    },
    source: { root: CWD },
  };
  md(
    "Input schema (the hello's `TabInfo` + `SourceInfo`, fixed at connect time; the body is the " +
      "composed prompt from sections A–G). A present `source.root` is the INTERIM aiui-app " +
      "detection signal: it gates the “web app under development” framing, the `aiui-app` tab " +
      "attribute, and the relative-paths line. The transcription note is TURN-dependent — " +
      "`intent-v1` appends it at fin only when the stream contains speech-transcribed text:\n" +
      "````ts\n" +
      `{
  tab?: { url?: string; title?: string; chromeTabId?: number;
          windowId?: number; tabIndex?: number; targetId?: string };  // CDP Target.TargetID
  source?: { root?: string };  // the dev server's absolute source root
}` +
      "\n````\n",
  );

  const wrapCase = (
    title: string,
    note: string,
    input: unknown,
    sections: string[],
    body: string,
  ): void => {
    caseNo += 1;
    const { text: wrapped, preambleLen } = wrapWithContextParts(sections, body);
    md(`### ${caseNo}. ${title}\n`);
    if (note) md(`${note} (\`preambleLen\` = ${preambleLen}.)\n`);
    md("Input:\n");
    md("````json\n" + JSON.stringify(input, jsonReplacer, 2) + "\n````\n");
    md("Rendered:\n");
    md("````text\n" + wrapped + "\n````\n");
    comments();
  };

  wrapCase(
    "Full hello (aiui app detected: every tab hint + source root) — the wrapped prompt",
    "The body starts right after the `---` rule.",
    fullHello,
    promptContextSections(fullHello as never),
    "make this wider",
  );

  const minimalHello = { tab: { title: "App", url: "http://localhost:5173/" } };
  wrapCase(
    "Minimal hello (title+url only, NO aiui app): the neutral opening, no dev framing",
    "",
    minimalHello,
    promptContextSections(minimalHello as never),
    "make this wider",
  );

  wrapCase(
    "A SPEECH turn (aiui hello + transcription note appended at fin)",
    "Input shows the hello; the note is turn-dependent, not hello-fixed.",
    fullHello,
    [...promptContextSections(fullHello as never), TRANSCRIPTION_NOTE],
    "make this wider",
  );

  const legacySelection = {
    text: "Mean: 42.7",
    sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
    cell: "meanValue",
    cellLoc: `${CWD}/src/model.ts:33`,
    tex: "\\bar{x} = 42.7",
  };
  wrapCase(
    "LEGACY selection section — text-concat (text modality) ONLY; retired from intent-v1",
    "intent-v1 now IGNORES the legacy context chunk entirely; this wording survives only for " +
      "`text-concat`'s submit-time selection.",
    legacySelection,
    selectionSections(legacySelection),
    "explain this",
  );

  wrapCase(
    "Bare client (no hello context): body passes through unwrapped",
    "",
    {},
    [],
    "just the body",
  );
}

md("## I. The MCP server's self-description (static strings, quoted verbatim)\n");

/** A static-text case (not executed — quoted from source, with its location). */
function quote(title: string, note: string, body: string): void {
  caseNo += 1;
  md(`### ${caseNo}. ${title}\n`);
  if (note) md(`${note}\n`);
  md("````text\n" + body + "\n````\n");
  comments();
}

quote(
  "Server `instructions` (server.ts) — the once-per-session lesson: the channel + the prompt vocabulary",
  "Imported from the source, so this quote can never drift. The correlation workflow lives HERE " +
    "(taught once), not in every turn's preamble.",
  INSTRUCTIONS,
);

quote(
  "The prompt's delivery envelope (commands/mcp.ts:124)",
  "Every lowered prompt reaches the session as an MCP notification; Claude Code renders it as the `<channel>` block the instructions describe. The channel controls `content` and `meta`; the block's final wording is Claude Code's.",
  'method: "notifications/claude/channel"\nparams: { content: <the wrapped prompt>, meta: { kind: "prompt", ...optionC attachment paths } }',
);

quote(
  "Tool: `channel_info` (tools.ts:130)",
  "",
  "Return this aiui channel's own info: its tag, pid, ppid, port, cwd, and the Claude Code session it's attached to (name, sessionId, status). Returns a JSON object.",
);

quote(
  "Tool: `page_tools_list` (tools.ts:72)",
  "",
  "List the tools that live in the connected browser page(s) under development (registered by the page's aiui instrumentation). Returns a JSON array of directory entries: clientId, ns (page namespace), url, tab, and each tool's name/description/inputSchema. Entries from the browser's active tab sort first and carry activeTab: true (when a client reports tab activation; otherwise the flag is simply absent). Call this FIRST to discover what's available, then invoke one with page_tools_call. The list is empty when no dev page is connected.",
);

quote(
  "Tool: `page_tools_call` (tools.ts:81)",
  "",
  "Invoke one of the browser page's tools (discover them with page_tools_list first) and return its JSON result. Args: { name (required), args? (must match that tool's inputSchema), ns? and clientId? to disambiguate }. When exactly one registered tool has the given name you may omit ns/clientId; if several pages expose the same name, the one on the browser's active tab wins — when that still doesn't single one out the call errors and lists the candidates (pass ns and/or clientId to pick one). Errors if no page is connected, no tool matches, the page is mid-reload, or the call times out.",
);

quote(
  "Tool: `channel_reload` (tools.ts:90)",
  "",
  "After you edit this channel's own source, reload its lowering layer in place — the format registry is rebuilt from the code now on disk, no session restart. Live websockets drop and reconnect on their own (an in-flight intent turn is abandoned; the page stays up), and the MCP stdio session and web port are unaffected. Returns { reloaded, generation, socketsDropped }. Only reloads the format-entry modules (processors, intent-v1) and their edits; changes deeper in the import graph still need a full relaunch.",
);

// ── write, backing up the previous round so annotations survive and diff ──────

const content = out.join("\n");
if (DOCS_MODE) {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
  const target = join(repoRoot, "docs", "guide", "prompt-rendering.md");
  writeFileSync(target, content);
  console.log(`wrote ${target} (${caseNo} cases, docs mode)`);
} else if (process.argv[2] !== undefined) {
  // Preview mode: a single copy at an explicit path, no backups.
  writeFileSync(process.argv[2], content);
  console.log(`wrote ${process.argv[2]} (${caseNo} cases)`);
} else {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
  const auditDir = join(repoRoot, "audit.local");
  mkdirSync(auditDir, { recursive: true });
  const pristine = join(auditDir, "render-audit.md");
  const markup = join(auditDir, "render-audit.markup.md");
  // Back the previous round up as a numbered PAIR, so any round diffs cleanly
  // against any other (and annotations survive regeneration).
  if (existsSync(pristine) || existsSync(markup)) {
    const versions = readdirSync(auditDir)
      .map((f) => /^render-audit(?:\.markup)?\.v(\d+)\.md$/.exec(f)?.[1])
      .filter((v): v is string => v !== undefined)
      .map(Number);
    const next = versions.length > 0 ? Math.max(...versions) + 1 : 1;
    if (existsSync(pristine)) {
      copyFileSync(pristine, join(auditDir, `render-audit.v${next}.md`));
    }
    if (existsSync(markup)) {
      copyFileSync(markup, join(auditDir, `render-audit.markup.v${next}.md`));
    }
    console.log(`backed up previous round as v${next}`);
  }
  writeFileSync(pristine, content);
  writeFileSync(markup, content);
  console.log(`wrote ${pristine} + .markup twin (${caseNo} cases)`);
}
