/**
 * Render-audit harness (uncommitted working tool).
 *
 * Drives every item→text render path in the lowering pipeline's render.ts, plus
 * the channel's context preamble and the MCP self-description strings, with
 * representative inputs, and emits the ACTUAL rendered output for each case as
 * one markdown document — so the audit reviews real outputs side by side
 * instead of spelunking the code.
 *
 * The annotate-iterate loop:
 *  - output goes to <repo>/audit.local/render-audit.md (gitignored via *.local)
 *  - every case ends with a `**Comments:**` block; the owner writes decisions
 *    there in place, and the agent reads them back to drive code changes
 *  - each run first backs up the existing file to render-audit.v<N>.md, so an
 *    annotated round survives regeneration and `diff v<N> render-audit.md`
 *    shows exactly what a code change did to the outputs
 *
 * Run: pnpm exec tsx render-audit.mts [output.md]   (from this package dir)
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type ComposedItem,
  type ComposeOptions,
  renderPrompt,
} from "@habemus-papadum/aiui-lowering-pipeline";
import {
  promptContextSections,
  selectionSections,
  wrapWithContextParts,
} from "./src/prompt-context";

const CWD = "/repo/app";
const out: string[] = [];
const md = (s: string): void => {
  out.push(s);
};

const NO_COMMENT = "_none yet_";
/** The owner's annotation slot — one per case, edited in place in the output. */
const comments = (): void => {
  md(`**Comments:**\n\n${NO_COMMENT}\n`);
};

let caseNo = 0;
/** Render `items` through the real pass 5 and emit the case as markdown. */
function show(
  title: string,
  note: string,
  items: ComposedItem[],
  options: ComposeOptions = { cwd: CWD },
): void {
  caseNo += 1;
  const composed = renderPrompt(items, [], "replace", options);
  md(`### ${caseNo}. ${title}\n`);
  if (note) md(`${note}\n`);
  md("````text\n" + composed.prompt + "\n````\n");
  comments();
}

/** A minimal text item. */
const text = (t: string): ComposedItem => ({ kind: "text", text: t, segment: 1 });

const SHOT_PATH = `${CWD}/.aiui-cache/traces/t1/shot_1.png`;

// ─────────────────────────────────────────────────────────────────────────────
md("# Render audit — every item→text path, actual outputs\n");
md(
  "Generated by `packages/aiui-claude-channel/render-audit.mts` against the worktree's real " +
    `\`renderPrompt\`. All cases use \`cwd: ${CWD}\` unless noted, so relativization is visible. ` +
    "Each output block is the exact composed prompt.\n",
);
md(
  "**How to annotate:** work in `render-audit.markup.md` (this file's identical twin) — " +
    "*meta-commentary* goes in a case's `**Comments:**` block (replacing “_none yet_”); " +
    "*concrete wording changes* you make by directly editing the rendered output text in place. " +
    "`render-audit.md` stays pristine; the agent diffs the two to pick up both kinds of feedback. " +
    "Each regeneration backs the previous round up as a numbered pair " +
    "(`render-audit.v<N>.md` / `render-audit.markup.v<N>.md`).\n",
);

md(
  "## A. Screenshots — the ONE form (bracket line + `<screenshot-metadata>` when elements were located)\n",
);

show("Viewport shot (bare bracket line, no element info by design)", "Trigger: `viewport: true`.", [
  text("look at the whole page"),
  { kind: "shot", marker: "shot_1", path: SHOT_PATH, viewport: true },
]);

show(
  "Region shot, no located components",
  "Trigger: empty `components`. Bracket line only, inline mid-sentence.",
  [
    text("this area"),
    { kind: "shot", marker: "shot_1", path: SHOT_PATH, components: [] },
    text("needs work"),
  ],
);

show(
  "Region shot with elements and cells (the rich block)",
  'Trigger: components with sources and cells; one `containment: "within"` anchor; one `source: "unknown"` (dropped attr); one cell without a source.',
  [
    text("make this wider"),
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Legend",
          source: `${CWD}/src/Legend.tsx:30:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [{ name: "colorScale", source: `${CWD}/src/Legend.tsx:41:8` }, { name: "ticks" }],
        },
        {
          component: "Plot",
          source: "unknown",
          rect: { x: 0, y: 0, w: 10, h: 10 },
        },
        {
          component: "Panel",
          source: `${CWD}/src/Panel.tsx:5:1`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          containment: "within",
        },
      ],
    },
  ],
);

show(
  "Cell overflow (>4 cells → `cells-omitted`)",
  "Trigger: 6 cells on one element; the first 4 list, 2 collapse.",
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Dashboard",
          source: `${CWD}/src/Dash.tsx:1:1`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [1, 2, 3, 4, 5, 6].map((n) => ({ name: `cell${n}` })),
        },
      ],
    },
  ],
);

show(
  "Element overflow (>8 components → `elements-omitted`)",
  "Trigger: 10 components; document order keeps the first 8.",
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: Array.from({ length: 10 }, (_, i) => ({
        component: `Widget${i + 1}`,
        source: `${CWD}/src/W${i + 1}.tsx:1:1`,
        rect: { x: 0, y: 0, w: 10, h: 10 },
      })),
    },
  ],
);

show(
  "Missing image (capture denied/unavailable)",
  "Trigger: no `path`. The marker keeps the reference alive.",
  [text("as I showed you"), { kind: "shot", marker: "shot_2", components: [] }],
);

show(
  "Pasted image (clipboard, not screen)",
  'Trigger: `origin: "paste"` — its own tag so the model can\'t mistake clipboard for screen.',
  [
    text("use this mockup"),
    { kind: "shot", marker: "shot_1", path: SHOT_PATH, origin: "paste", components: [] },
  ],
);

show("Video-share frame, smart mode (captured on change)", 'Trigger: `share.mode: "smart"`.', [
  {
    kind: "shot",
    marker: "shot_1",
    path: SHOT_PATH,
    share: { ordinal: 1, mode: "smart", offsetMs: 0 },
    components: [],
  },
]);

show(
  "Video-share frame, continuous mode (capture time rides with the path)",
  'Trigger: `share.mode: "continuous"`, offset 12340ms.',
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      share: { ordinal: 1, mode: "continuous", offsetMs: 12340 },
      components: [],
    },
  ],
);

show(
  "Path outside cwd stays absolute; XML escaping in names",
  'Trigger: shot path outside cwd; a component named `A<B> & "C"`.',
  [
    {
      kind: "shot",
      marker: "shot_1",
      path: "/elsewhere/traces/shot_9.png",
      components: [
        {
          component: 'A<B> & "C"',
          source: `${CWD}/src/AB.tsx:2:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
        },
      ],
    },
  ],
);

md("## C. Code selections\n");

show("Short code selection with locator (inlined)", "Trigger: ≤240 chars.", [
  text("rename this"),
  {
    kind: "code-selection",
    marker: "code_1",
    text: "const x = 1;",
    sourceLoc: `${CWD}/src/a.ts:5:1`,
    lines: 1,
  },
]);

show("Short code selection, no locator", 'Trigger: `sourceLoc` absent → "the selection".', [
  { kind: "code-selection", marker: "code_1", text: "let y = 2;" },
]);

show("Long code selection (fenced block with line count)", "Trigger: >240 chars.", [
  text("refactor this"),
  {
    kind: "code-selection",
    marker: "code_1",
    text: Array.from(
      { length: 8 },
      (_, i) => `export function helper${i}(input: number): number { return input * ${i}; }`,
    ).join("\n"),
    sourceLoc: `${CWD}/src/helpers.ts:1-8`,
    lines: 8,
  },
  text("into one generic"),
]);

md("## D. App (on-screen) selections\n");

show("Short app selection, no attribution", "", [
  { kind: "app-selection", marker: "sel_1", text: "42.7" },
]);

show("Short app selection, full attribution", "Trigger: sourceLoc + cell + cellLoc.", [
  text("why is"),
  {
    kind: "app-selection",
    marker: "sel_1",
    text: "42.7",
    sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
    cell: "meanValue",
    cellLoc: `${CWD}/src/model.ts:33`,
  },
  text("so high"),
]);

show("App selection of rendered mathematics (TeX attribution)", "", [
  {
    kind: "app-selection",
    marker: "sel_2",
    text: "∂u/∂t = D ∂²u/∂x²",
    sourceLoc: `${CWD}/src/Equation.tsx:8:2`,
    tex: "\\frac{\\partial u}{\\partial t} = D \\frac{\\partial^2 u}{\\partial x^2}",
  },
]);

show("Long app selection (fenced)", "Trigger: >240 chars of page text.", [
  {
    kind: "app-selection",
    marker: "sel_1",
    text: "The diffusion simulation shows temperature spreading through the rod over time. ".repeat(
      4,
    ),
    sourceLoc: `${CWD}/src/Explainer.tsx:3:1`,
    cell: "narrative",
  },
]);

md("## E. Boundaries\n");

show("Navigation (same tab)", "", [
  text("the old chart"),
  {
    kind: "navigation",
    from: "https://app.test/dashboard?tab=1",
    to: "https://app.test/detail#sec",
  },
  text("now this one"),
]);

show(
  "Navigation with unparseable URLs",
  "Trigger: strings `new URL` rejects → raw string; empty → `?`.",
  [{ kind: "navigation", from: "not a url", to: "" }],
);

show("Tab switch", "", [
  text("compare with"),
  {
    kind: "tab-switch",
    from: "https://app.test/a",
    to: "https://docs.test/api/ref",
    fromTab: 1,
    toTab: 2,
  },
]);

md("## F. Corrections (note policy)\n");

{
  caseNo += 1;
  const composed = renderPrompt(
    [text("make the plot tall her")],
    [{ original: "tall her", instruction: "taller", applied: false }],
    "note",
    { cwd: CWD },
  );
  md(`### ${caseNo}. Unapplied correction under \`policy: "note"\`\n`);
  md("Trigger: a correction the patcher could not apply → appended parenthetical.\n");
  md("````text\n" + composed.prompt + "\n````\n");
  comments();
}

md("## G. A full interleaved turn (joins, trims, blank-line separation)\n");

show(
  "Prose · rich shot · prose · selection · navigation · viewport shot",
  "Watch the seams: single-space joins, the multi-line block's surrounding newlines (note the trailing space before each block's leading newline), leading/trailing trim.",
  [
    text("make this legend"),
    {
      kind: "shot",
      marker: "shot_1",
      path: SHOT_PATH,
      components: [
        {
          component: "Legend",
          source: `${CWD}/src/Legend.tsx:30:2`,
          rect: { x: 0, y: 0, w: 10, h: 10 },
          cells: [{ name: "colorScale" }],
        },
      ],
    },
    text("wider, and align it with"),
    {
      kind: "app-selection",
      marker: "sel_1",
      text: "Mean: 42.7",
      sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
    },
    { kind: "navigation", from: "https://app.test/a", to: "https://app.test/b" },
    text("then check the whole page"),
    {
      kind: "shot",
      marker: "shot_2",
      path: `${CWD}/.aiui-cache/traces/t1/shot_2.png`,
      viewport: true,
    },
  ],
);

md("## H. The context preamble (channel, `prompt-context.ts`)\n");

{
  const fullHello = {
    tab: {
      title: "Spectra — dev",
      url: "http://localhost:5173/",
      chromeTabId: 712,
      windowId: 3,
      tabIndex: 0,
      targetId: "F00D",
    },
    source: { root: CWD },
  };
  const sections = promptContextSections(fullHello as never);
  const { text: wrapped, preambleLen } = wrapWithContextParts(sections, "make this wider");
  caseNo += 1;
  md(`### ${caseNo}. Full hello (tab with every hint + source root) — the wrapped prompt\n`);
  md(`\`preambleLen\` = ${preambleLen}; the body starts right after the \`---\` rule.\n`);
  md("````text\n" + wrapped + "\n````\n");
  comments();

  const minimal = promptContextSections({
    tab: { title: "App", url: "http://localhost:5173/" },
  } as never);
  caseNo += 1;
  md(`### ${caseNo}. Minimal hello (title+url only, no source root)\n`);
  md("````text\n" + wrapWithContextParts(minimal, "make this wider").text + "\n````\n");
  comments();

  const sel = selectionSections({
    text: "Mean: 42.7",
    sourceLoc: `${CWD}/src/Readout.tsx:12:4`,
    cell: "meanValue",
    cellLoc: `${CWD}/src/model.ts:33`,
    tex: "\\bar{x} = 42.7",
  });
  caseNo += 1;
  md(
    `### ${caseNo}. LEGACY selection section (context-chunk path: text modality / old clients only)\n`,
  );
  md("````text\n" + wrapWithContextParts(sel, "explain this").text + "\n````\n");
  comments();

  caseNo += 1;
  md(`### ${caseNo}. Bare client (no hello context): body passes through unwrapped\n`);
  md("````text\n" + wrapWithContextParts([], "just the body").text + "\n````\n");
  comments();
}

md("## I. The MCP server's self-description (static strings, quoted verbatim)\n");

/** A static-text case (not executed — quoted from source, with its location). */
function quote(title: string, note: string, body: string): void {
  caseNo += 1;
  md(`### ${caseNo}. ${title}\n`);
  if (note) md(`${note}\n`);
  md("````text\n" + body + "\n````\n");
  comments();
}

quote(
  "Server `instructions` (server.ts:23) — what Claude Code shows the agent about the channel",
  "",
  'This is the aiui channel, a one-way event feed into your session. Events arrive as `<channel source="aiui" ...>` blocks: read them and act on them as context. This channel is one-way — there is nothing to reply to and no tool to call back into it.',
);

quote(
  "The prompt's delivery envelope (commands/mcp.ts:124)",
  "Every lowered prompt reaches the session as an MCP notification; Claude Code renders it as the `<channel>` block the instructions describe. The channel controls `content` and `meta`; the block's final wording is Claude Code's.",
  'method: "notifications/claude/channel"\nparams: { content: <the wrapped prompt>, meta: { kind: "prompt", ...optionC attachment paths } }',
);

quote(
  "Tool: `channel_info` (tools.ts:130)",
  "",
  "Return this aiui channel's own info: its tag, pid, ppid, port, cwd, and the Claude Code session it's attached to (name, sessionId, status). Returns a JSON object.",
);

quote(
  "Tool: `page_tools_list` (tools.ts:72)",
  "",
  "List the tools that live in the connected browser page(s) under development (registered by the aiui dev overlay). Returns a JSON array of directory entries: clientId, ns (page namespace), url, tab, and each tool's name/description/inputSchema. Entries from the browser's active tab sort first and carry activeTab: true (when a client reports tab activation; otherwise the flag is simply absent). Call this FIRST to discover what's available, then invoke one with page_tools_call. The list is empty when no dev page is connected.",
);

quote(
  "Tool: `page_tools_call` (tools.ts:81)",
  "",
  "Invoke one of the browser page's tools (discover them with page_tools_list first) and return its JSON result. Args: { name (required), args? (must match that tool's inputSchema), ns? and clientId? to disambiguate }. When exactly one registered tool has the given name you may omit ns/clientId; if several pages expose the same name, the one on the browser's active tab wins — when that still doesn't single one out the call errors and lists the candidates (pass ns and/or clientId to pick one). Errors if no page is connected, no tool matches, the page is mid-reload, or the call times out.",
);

quote(
  "Tool: `channel_reload` (tools.ts:90)",
  "",
  "After you edit this channel's own source, reload its lowering layer in place — the format registry is rebuilt from the code now on disk, no session restart. Live websockets drop and reconnect on their own (an in-flight intent turn is abandoned; the page stays up), and the MCP stdio session and web port are unaffected. Returns { reloaded, generation, socketsDropped }. Only reloads the format-entry modules (processors, intent-v1) and their edits; changes deeper in the import graph still need a full relaunch.",
);

// ── write, backing up the previous round so annotations survive and diff ──────

const content = out.join("\n");
if (process.argv[2] !== undefined) {
  // Preview mode: a single copy at an explicit path, no backups.
  writeFileSync(process.argv[2], content);
  console.log(`wrote ${process.argv[2]} (${caseNo} cases)`);
} else {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
  const auditDir = join(repoRoot, "audit.local");
  mkdirSync(auditDir, { recursive: true });
  const pristine = join(auditDir, "render-audit.md");
  const markup = join(auditDir, "render-audit.markup.md");
  // Back the previous round up as a numbered PAIR, so any round diffs cleanly
  // against any other (and annotations survive regeneration).
  if (existsSync(pristine) || existsSync(markup)) {
    const versions = readdirSync(auditDir)
      .map((f) => /^render-audit(?:\.markup)?\.v(\d+)\.md$/.exec(f)?.[1])
      .filter((v): v is string => v !== undefined)
      .map(Number);
    const next = versions.length > 0 ? Math.max(...versions) + 1 : 1;
    if (existsSync(pristine)) {
      copyFileSync(pristine, join(auditDir, `render-audit.v${next}.md`));
    }
    if (existsSync(markup)) {
      copyFileSync(markup, join(auditDir, `render-audit.markup.v${next}.md`));
    }
    console.log(`backed up previous round as v${next}`);
  }
  writeFileSync(pristine, content);
  writeFileSync(markup, content);
  console.log(`wrote ${pristine} + .markup twin (${caseNo} cases)`);
}
