/**
 * providers.ts — built-in launcher recipes for well-known languages.
 *
 * `aiui setup-lsp` is Claude-driven: for an exotic language it works out how to
 * install + launch the server and hand-writes the launcher. But for common
 * languages that ship as npm binaries, a deterministic recipe is better than
 * asking the model to rediscover it each time — so python (pyright) and
 * typescript (typescript-language-server) have built-in recipes here. A recipe
 * emits the SAME executable-launcher + manifest format as a hand-authored one,
 * and is still probe-tested before being recorded — it is a shortcut, not a
 * hardcoded server the channel special-cases.
 *
 * The emitted launcher is **portable**: it computes the project root from its own
 * on-disk location and resolves the server from the project's own
 * `node_modules/.bin`, with no absolute machine paths baked in. That is what
 * lets a `.aiui/lsp/` setup be committed and work on any clone after `install`.
 * (The `require.resolve` below is only a build-time availability check — "is this
 * server installable in this environment" — not a path baked into the script.)
 */

import { readdirSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

const require = createRequire(import.meta.url);

export interface BuiltLauncher {
  language: string;
  languageId: string;
  extensions: string[];
  /** The executable launcher's contents (a shell script with a shebang). */
  script: string;
  /** Human label recorded as `name` in the manifest. */
  name: string;
  initializationOptions?: Record<string, unknown>;
}

export interface ProviderRecipe {
  language: string;
  languageId: string;
  extensions: string[];
  /** Resolve the server for this project; throws with an actionable message if
   * the server binary can't be found (so setup can report + skip it). */
  build(projectRoot: string): BuiltLauncher;
}

const shebang = "#!/usr/bin/env bash\n";

/**
 * A **portable** launcher. It lives at `<root>/.aiui/lsp/<lang>/launch`, so the
 * project root is three levels up from the script; it computes that at runtime
 * and resolves the language server from the project's own `node_modules/.bin`.
 * No absolute machine paths, so the launcher can be committed and works on any
 * clone once dependencies are installed. `serverBin` is the bin name the server
 * package publishes (pnpm/npm links it into `.bin`), e.g.
 * `typescript-language-server` or `pyright-langserver`.
 */
function launcherScript(lang: string, serverBin: string): string {
  return (
    `${shebang}` +
    `# aiui LSP launcher — ${lang}. Generated by \`aiui setup-lsp\`.\n` +
    `# Speaks LSP on stdio; the channel/reader spawns this and pipes bytes.\n` +
    `# Portable: ROOT is this project (the launcher lives at .aiui/lsp/<lang>/launch,\n` +
    `# three levels down); the server resolves from the project's own node_modules\n` +
    `# and node comes from PATH — no absolute machine paths.\n` +
    `ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"\n` +
    `exec "$ROOT/node_modules/.bin/${serverBin}" --stdio "$@"\n`
  );
}

/** pyright's stdio language server. */
const python: ProviderRecipe = {
  language: "python",
  languageId: "python",
  extensions: [".py", ".pyi"],
  build(): BuiltLauncher {
    // Availability check only (not a path baked into the launcher): is pyright
    // installable in this environment? The portable launcher resolves the
    // project's own `node_modules/.bin/pyright-langserver` at runtime.
    try {
      require.resolve("pyright/langserver.index.js");
    } catch {
      throw new Error("pyright not found — `pnpm add -D pyright` (or install it globally)");
    }
    const version = safeVersion("pyright");
    return {
      language: "python",
      languageId: "python",
      extensions: [".py", ".pyi"],
      script: launcherScript("python (pyright)", "pyright-langserver"),
      name: `pyright${version ? ` ${version}` : ""}`,
    };
  },
};

/** typescript-language-server (wraps tsserver) for TS/JS. */
const typescript: ProviderRecipe = {
  language: "typescript",
  languageId: "typescript",
  extensions: [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"],
  build(): BuiltLauncher {
    // Availability check only (not a path baked into the launcher): is
    // typescript-language-server installable here? The portable launcher resolves
    // the project's own `node_modules/.bin/typescript-language-server` at runtime.
    try {
      require.resolve("typescript-language-server/lib/cli.mjs");
    } catch {
      throw new Error(
        "typescript-language-server not found — `pnpm add -D typescript-language-server typescript`",
      );
    }
    // No `initializationOptions.tsserver.path`: an absolute tsserver path would
    // break portability. typescript-language-server finds the project's own
    // `typescript` from its cwd (the backend/probe spawn the launcher with cwd =
    // project root), so the project just needs `typescript` as a dependency.
    const version = safeVersion("typescript-language-server");
    return {
      language: "typescript",
      languageId: "typescript",
      extensions: typescript.extensions,
      script: launcherScript(
        "typescript (typescript-language-server)",
        "typescript-language-server",
      ),
      name: `typescript-language-server${version ? ` ${version}` : ""}`,
    };
  },
};

export const PROVIDERS: Record<string, ProviderRecipe> = { python, typescript };

/** Scan a project (shallowly recursive, skipping heavy dirs) for extensions that
 * a built-in provider owns; returns the provider keys, in a stable order. */
export function detectLanguages(projectRoot: string, maxDepth = 4): string[] {
  const extToProvider = new Map<string, string>();
  for (const [key, recipe] of Object.entries(PROVIDERS)) {
    for (const ext of recipe.extensions) extToProvider.set(ext, key);
  }
  const found = new Set<string>();
  const skip = new Set([
    "node_modules",
    ".git",
    ".venv",
    "venv",
    "dist",
    "build",
    "__pycache__",
    ".aiui",
    ".aiui-cache",
  ]);
  const walk = (dir: string, depth: number): void => {
    if (depth > maxDepth || found.size === Object.keys(PROVIDERS).length) return;
    let entries: import("node:fs").Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.isDirectory()) {
        if (!skip.has(e.name) && !e.name.startsWith(".")) walk(join(dir, e.name), depth + 1);
      } else {
        const dot = e.name.lastIndexOf(".");
        if (dot < 0) continue;
        const provider = extToProvider.get(e.name.slice(dot).toLowerCase());
        if (provider) found.add(provider);
      }
    }
  };
  walk(projectRoot, 0);
  return Object.keys(PROVIDERS).filter((k) => found.has(k));
}

function safeVersion(pkg: string): string | undefined {
  try {
    return (require(`${pkg}/package.json`) as { version?: string }).version;
  } catch {
    return undefined;
  }
}
