import { defineConfig } from "vitepress";
// The sidebar is generated by `scripts/docs-gen.mjs` (pnpm docs:gen) from the packages/*
// glob — adding a package needs no edit here. The file is gitignored; run docs:gen first.
import sidebar from "./sidebar.generated.json" with { type: "json" };

export default defineConfig({
  title: "pdum_aiui",
  description: "Docs for the @habemus-papadum aiui monorepo — packages, guides, and API reference.",
  // GitHub Pages / any subpath is fine later; "/" works for local serving now.
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  // Generated API pages and imported notes can contain links we don't want to hard-fail on.
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/" },
      { text: "Packages", link: "/packages/" },
    ],
    sidebar,
    socialLinks: [{ icon: "github", link: "https://github.com/habemus-papadum/pdum_aiui" }],
    search: { provider: "local" },
    outline: { level: [2, 3] },
  },
});
