import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";
// The sidebar is generated by `scripts/docs-gen.mjs` (pnpm docs:gen) from the packages/*
// glob — adding a package needs no edit here. The file is gitignored; run docs:gen first.
import sidebar from "./sidebar.generated.json" with { type: "json" };

// `withMermaid` wraps the config so ```mermaid fences render as SVG: it registers a
// client-only <Mermaid> component (dynamic-imports `mermaid` in onMounted, so the build
// stays SSR-safe) and re-renders on the appearance toggle. Light uses the `neutral`
// theme; the component swaps to mermaid's `dark` theme when VitePress sets `.dark` on
// <html>, so diagrams read in both schemes.
export default withMermaid(
  defineConfig({
    title: "pdum_aiui",
    description:
      "Docs for the @habemus-papadum aiui monorepo — packages, guides, and API reference.",
    // "/" works for local serving; the Pages workflow sets DOCS_BASE to the repo
    // subpath (e.g. "/pdum_aiui/") so assets resolve on project Pages.
    base: process.env.DOCS_BASE ?? "/",
    // Mermaid is dynamic-imported in the browser at page view, so `vitepress dev`
    // discovers its CommonJS dependencies (dayjs, debug, sanitize-url) too late to
    // pre-bundle them — they get served raw, and the missing ESM interop throws
    // "does not provide an export named 'default'" (white screen). Pre-including
    // mermaid bundles the whole graph with interop up front. Registry deps only —
    // never optimizeDeps.include a workspace package (lockfile-keyed cache).
    vite: {
      optimizeDeps: { include: ["mermaid", "dayjs", "debug", "@braintree/sanitize-url"] },
    },
    cleanUrls: true,
    lastUpdated: true,
    // Generated API pages and imported notes can contain links we don't want to hard-fail on.
    ignoreDeadLinks: true,
    themeConfig: {
      nav: [
        { text: "Guide", link: "/guide/" },
        { text: "Packages", link: "/packages/" },
      ],
      sidebar,
      socialLinks: [{ icon: "github", link: "https://github.com/habemus-papadum/pdum_aiui" }],
      search: { provider: "local" },
      outline: { level: [2, 3] },
    },
    mermaid: {
      theme: "neutral",
      // Pin a system font stack (available at first paint) so mermaid measures node
      // boxes in the same font it renders them. VitePress's default web font (Inter)
      // can load *after* mermaid measures on mount, undersizing multi-line nodes and
      // clipping their last line — a system stack sidesteps that race.
      fontFamily:
        'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    },
  }),
);
