#!/usr/bin/env node
/**
 * Regenerate src/styles.generated.ts from the stylesheets. The CSS files are
 * the source of truth (they ARE the `./style.css` and `./themes/*.css`
 * subpaths); this module carries the same text as plain TypeScript strings,
 * so a library that embeds the inspector can inject a <style> itself without
 * importing CSS — a CSS import, even `?inline`, has no type under the
 * tsconfig of a consumer that compiles this package's source. Committed, and
 * guarded by src/styles-export.test.ts; run `pnpm gen:styles` after editing
 * any stylesheet.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const src = join(dirname(fileURLToPath(import.meta.url)), "..", "src");
const literal = (file) => JSON.stringify(readFileSync(join(src, file), "utf8"));
const out = `// GENERATED by scripts/gen-styles.mjs from style.css and themes/*.css — do not
// edit by hand; run \`pnpm gen:styles\` after changing a stylesheet.
export const BASE = ${literal("style.css")};
export const AIUI = ${literal("themes/aiui.css")};
export const TERMINAL = ${literal("themes/terminal.css")};
`;
const target = join(src, "styles.generated.ts");
writeFileSync(target, out);
// House format, so the committed file passes `biome check` as written.
execFileSync("pnpm", ["exec", "biome", "format", "--write", target], { stdio: "ignore" });
console.log("wrote src/styles.generated.ts");
