/**
 * glyph.ts — the geometry of the notation (playbook layer 1: pure, realm-free,
 * tested). Everything here is numbers and path strings; nothing imports a
 * framework.
 *
 * ## The design
 *
 * Each base is a rectangular cell whose **bottom edge** carries a bump — the
 * pairing edge. The top edge is flat. Two independent features encode the two
 * things a reader needs to see:
 *
 * - **bump family** (`round` for A·T, `angular` for G·C) says *which pair*;
 * - **polarity** (`tooth` protruding down, `socket` cut up) says *which member*.
 *
 * A third feature, the **filled half**, is shared by both members of a pair
 * (top for A·T, bottom for G·C). It is what makes the duplex legible at a
 * glance — see `duplexLayout`.
 *
 * ## Why the edges mesh
 *
 * Draw a strand left→right on top, and its reverse complement below rotated
 * 180°. Position *i* of the bottom row then shows `rot180(glyph(comp(sᵢ)))`.
 * Rotating a cell about its centre maps `(x, y) → (W − x, H − y)`, so the
 * partner's *bottom* edge becomes the *top* edge the pairing line actually
 * sees. Writing the bottom edge as `H + polarity · amp · s(x)` for a bump `s`
 * that is symmetric about the cell centre, the two curves coincide exactly when
 *
 *     polarity(X) = −polarity(comp(X))   and   family(X) = family(comp(X)),
 *
 * which is precisely the table in `PROFILE`. Both members of a pair are
 * generated by this one parameterised builder with the sign flipped, so the
 * tooth and its socket cannot drift apart the way two hand-drawn paths would.
 * `glyph.test.ts` pins it numerically on the sampled curves.
 */
import { type Base, complement, reverseComplement } from "./dna";

/** A point in glyph-local coordinates (y grows downward, as in SVG). */
export interface Pt {
  x: number;
  y: number;
}

/** One path segment: a line if it carries no controls, else a cubic Bézier. */
export type Seg = { to: Pt } | { c1: Pt; c2: Pt; to: Pt };

function isCubic(seg: Seg): seg is { c1: Pt; c2: Pt; to: Pt } {
  return "c1" in seg;
}

/** The dimensions every path is generated from. */
export interface GlyphMetrics {
  /** Cell width — glyphs sit flush, so this is also the horizontal pitch. */
  width: number;
  /** Cell height, flat top edge to the bump's baseline. */
  height: number;
  /** How far a tooth protrudes below the baseline (and a socket cuts above it). */
  amp: number;
  /** Half-width of the bump along the edge. */
  halfWidth: number;
}

export const DEFAULT_METRICS: GlyphMetrics = {
  width: 11,
  height: 15,
  amp: 3.4,
  halfWidth: 3.2,
};

/** Round bumps belong to A·T, angular ones to G·C. */
export type BumpFamily = "round" | "angular";

/** `1` protrudes below the baseline (a tooth); `-1` cuts above it (a socket). */
export type Polarity = 1 | -1;

export interface BaseProfile {
  family: BumpFamily;
  polarity: Polarity;
  /** Which half of the cell is solid — shared by both members of a pair. */
  fill: "top" | "bottom";
}

/**
 * The notation itself. Complements share a family and a filled half, and oppose
 * in polarity — the three facts every visual claim in this app rests on.
 */
export const PROFILE = {
  A: { family: "round", polarity: 1, fill: "top" },
  T: { family: "round", polarity: -1, fill: "top" },
  G: { family: "angular", polarity: 1, fill: "bottom" },
  C: { family: "angular", polarity: -1, fill: "bottom" },
} as const satisfies Record<Base, BaseProfile>;

/** Where the bottom edge starts, in cell-local coordinates. */
export function bottomEdgeStart(m: GlyphMetrics): Pt {
  return { x: 0, y: m.height };
}

/**
 * The bottom (pairing) edge, left→right, as the single source of truth: both
 * the rendered path and the sampled curve the tessellation test checks are
 * derived from this one list.
 */
export function bottomEdgeSegments(base: Base, m: GlyphMetrics): Seg[] {
  const { width: w, height: h, amp, halfWidth: hw } = m;
  const { family, polarity } = PROFILE[base];
  const cx = w / 2;
  const peak = h + polarity * amp;

  if (family === "angular") {
    return [
      { to: { x: cx - hw, y: h } },
      { to: { x: cx, y: peak } },
      { to: { x: cx + hw, y: h } },
      { to: { x: w, y: h } },
    ];
  }
  // A rounded tab: control points placed symmetrically about the centre, so the
  // curve is its own mirror image and flips exactly with `polarity`.
  const lift = h + polarity * amp * 1.28;
  return [
    { to: { x: cx - hw, y: h } },
    {
      c1: { x: cx - hw * 0.72, y: lift },
      c2: { x: cx + hw * 0.72, y: lift },
      to: { x: cx + hw, y: h },
    },
    { to: { x: w, y: h } },
  ];
}

/** Segments → SVG path commands (no leading `M`; the caller places the pen). */
export function segmentsPath(segs: readonly Seg[]): string {
  return segs
    .map((s) =>
      isCubic(s)
        ? `C ${s.c1.x} ${s.c1.y} ${s.c2.x} ${s.c2.y} ${s.to.x} ${s.to.y}`
        : `L ${s.to.x} ${s.to.y}`,
    )
    .join(" ");
}

function cubicAt(p0: Pt, c1: Pt, c2: Pt, p1: Pt, t: number): Pt {
  const u = 1 - t;
  const a = u * u * u;
  const b = 3 * u * u * t;
  const c = 3 * u * t * t;
  const d = t * t * t;
  return {
    x: a * p0.x + b * c1.x + c * c2.x + d * p1.x,
    y: a * p0.y + b * c1.y + c * c2.y + d * p1.y,
  };
}

/**
 * Sample a segment list into a dense polyline — the form the tessellation test
 * compares, so it checks the geometry that actually gets rendered.
 */
export function sampleSegments(start: Pt, segs: readonly Seg[], perSegment = 24): Pt[] {
  const pts: Pt[] = [start];
  let from = start;
  for (const seg of segs) {
    for (let i = 1; i <= perSegment; i++) {
      const t = i / perSegment;
      pts.push(
        isCubic(seg)
          ? cubicAt(from, seg.c1, seg.c2, seg.to, t)
          : { x: from.x + (seg.to.x - from.x) * t, y: from.y + (seg.to.y - from.y) * t },
      );
    }
    from = seg.to;
  }
  return pts;
}

/** The closed outline of a glyph: flat top, straight sides, bumped bottom. */
export function glyphOutlinePath(base: Base, m: GlyphMetrics): string {
  const start = bottomEdgeStart(m);
  const edge = segmentsPath(bottomEdgeSegments(base, m));
  return `M ${start.x} ${start.y} ${edge} L ${m.width} 0 L 0 0 Z`;
}

/** The solid half — the two-tone fill that makes a pairing visible. */
export function glyphFillPath(base: Base, m: GlyphMetrics): string {
  const mid = m.height / 2;
  if (PROFILE[base].fill === "top") {
    return `M 0 0 L ${m.width} 0 L ${m.width} ${mid} L 0 ${mid} Z`;
  }
  const start = bottomEdgeStart(m);
  const edge = segmentsPath(bottomEdgeSegments(base, m));
  return `M ${start.x} ${start.y} ${edge} L ${m.width} ${mid} L 0 ${mid} Z`;
}

/**
 * A viewBox with room for a bump on either edge, identical for every base so
 * glyphs align when set inline in a line of text.
 */
export function glyphViewBox(m: GlyphMetrics): string {
  return `0 ${-m.amp} ${m.width} ${m.height + 2 * m.amp}`;
}

// --- duplex layout ------------------------------------------------------------

/** One glyph placed in a diagram. */
export interface PlacedGlyph {
  base: Base;
  /** Column index along the duplex. */
  index: number;
  x: number;
  y: number;
  /** Whether this cell is turned 180° — true for the rotated partner strand. */
  rotated: boolean;
}

export interface DuplexLayout {
  top: PlacedGlyph[];
  bottom: PlacedGlyph[];
  width: number;
  height: number;
}

/**
 * Lay out a strand above its partner.
 *
 * With `rotateBottom` (the default) the lower row is the reverse complement
 * *turned 180°* — which puts `comp(sᵢ)` under `sᵢ` and meshes the edges. Set it
 * false to show the partner the way it is normally written, 5'→3' left to
 * right: the same strand, unturned, where nothing lines up. Toggling between
 * the two is the argument the notation is making.
 */
export function duplexLayout(
  seq: readonly Base[],
  m: GlyphMetrics,
  opts: { rotateBottom?: boolean } = {},
): DuplexLayout {
  const rotateBottom = opts.rotateBottom ?? true;
  const partner = reverseComplement(seq);
  const top: PlacedGlyph[] = seq.map((base, index) => ({
    base,
    index,
    x: index * m.width,
    y: 0,
    rotated: false,
  }));
  const bottom: PlacedGlyph[] = seq.map((base, index) => ({
    base: rotateBottom ? complement(base) : partner[index],
    index,
    x: index * m.width,
    y: m.height,
    rotated: rotateBottom,
  }));
  return { top, bottom, width: seq.length * m.width, height: 2 * m.height };
}

/**
 * The SVG transform placing a cell in the diagram: a translate, plus — for the
 * partner row — a 180° turn about the cell's own centre. This is the rotation
 * `glyph.test.ts` verifies arithmetically, so the drawn diagram and the proof
 * are the same operation.
 */
export function placedTransform(g: PlacedGlyph, m: GlyphMetrics): string {
  const move = `translate(${g.x} ${g.y})`;
  return g.rotated ? `${move} rotate(180 ${m.width / 2} ${m.height / 2})` : move;
}

/** The viewBox for a duplex diagram, with room for a bump on either outer edge. */
export function duplexViewBox(layout: DuplexLayout, m: GlyphMetrics): string {
  return `0 ${-m.amp} ${layout.width} ${layout.height + 2 * m.amp}`;
}
