#!/usr/bin/env node
/**
 * report.mjs — render a census snapshot as a readable schema reference.
 *
 *   node report.mjs snapshots/2026-07-26.json > SCHEMA.md
 *
 * The snapshot is the machine artifact (diffable, complete); this is the human
 * one. It is regenerated, never hand-edited — so it can never drift from what
 * is actually on disk, which is the whole point.
 */

import { readFile } from "node:fs/promises";

const file = process.argv[2];
if (!file) {
  console.error("usage: node report.mjs <snapshot.json>");
  process.exit(2);
}
const snap = JSON.parse(await readFile(file, "utf8"));
const out = [];
const w = (s = "") => out.push(s);

const n = (x) => x.toLocaleString("en-US");
const pct = (x) => `${(x * 100).toFixed(1)}%`;
const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s) => `\`${esc(s)}\``;

// ---------------------------------------------------------------------------

w(`# Claude Code transcript schema`);
w();
w(`> Generated by \`report.mjs\` from \`${file}\`. Do not hand-edit — re-run the census.`);
w();
const c = snap.corpus;
w(
  `Observed **${n(c.records)} records** across **${n(c.files)} files** (${(c.bytes / 1e6).toFixed(0)} MB)`,
);
w(`spanning \`${c.timestampRange[0]}\` → \`${c.timestampRange[1]}\`.`);
w(`Parse errors: ${n(c.parseErrors)}.`);
w();

// --- on-disk layout --------------------------------------------------------

w(`## On-disk layout`);
w();
w(`| file kind | count |`);
w(`| --- | ---: |`);
for (const [k, v] of Object.entries(c.fileKinds)) w(`| \`${k}\` | ${n(v)} |`);
w();
w(`A flat \`<project>/*.jsonl\` glob sees only the \`session\` files —`);
w(
  `**${pct(1 - c.fileKinds.session / c.files)} of files here live under \`<sessionId>/subagents/\`** and would be missed.`,
);
w();

// --- versions / models -----------------------------------------------------

w(`## Claude Code builds in this corpus`);
w();
const versions = Object.keys(c.ccVersions).sort(cmpVersion);
w(`${versions.length} builds, \`${versions[0]}\` … \`${versions.at(-1)}\`.`);
w(`Every field below is the union across all of them — presence percentages are`);
w(`therefore a *lower bound* for the newest build.`);
w();
w(`## Models`);
w();
w(`| model | assistant records |`);
w(`| --- | ---: |`);
for (const [m, v] of Object.entries(c.models)) w(`| \`${m}\` | ${n(v)} |`);
w();

// --- record shapes ---------------------------------------------------------

w(`## Record shapes`);
w();
w(`The transcript is a tagged union on \`type\`. Shape keys below use:`);
w(`\`record:<type>\` for the envelope, \`content:<type>:<block>\` for a`);
w(`\`message.content[]\` block, \`toolResult:<type>\` for the \`toolUseResult\` sidecar.`);
w(
  `Bracketed marks (\`[sidechain]\`, \`[meta]\`, \`[compactSummary]\`, \`[apiError]\`) are boolean`,
);
w(`discriminants that materially change the record's field set.`);
w();
w(`| shape | records | fields | seen in |`);
w(`| --- | ---: | ---: | --- |`);
for (const [k, s] of Object.entries(snap.shapes).sort((a, b) => b[1].count - a[1].count)) {
  w(
    `| \`${k}\` | ${n(s.count)} | ${Object.keys(s.paths).length} | ${Object.keys(s.fileKinds).join(", ")} |`,
  );
}
w();

// --- the billing surface, in full ------------------------------------------

w(`## Billing surface`);
w();
w(`There is **no cost field anywhere in the transcript.** Cost is always derived`);
w(`from these counters times an external price table.`);
w();
const asst = snap.shapes["record:assistant"];
if (asst) {
  w(`| path | types | presence | observed total |`);
  w(`| --- | --- | ---: | ---: |`);
  for (const [p, v] of Object.entries(asst.paths)) {
    if (!p.startsWith("message.usage")) continue;
    if (v.types.every((t) => t === "object" || t === "array")) continue;
    w(
      `| ${code(p)} | ${v.types.join(" \\| ")} | ${pct(v.presence)} | ${v.numeric ? n(v.numeric.sum) : "—"} |`,
    );
  }
  w();
}

// --- categorical fields ----------------------------------------------------

w(`## Categorical fields`);
w();
w(`Low-cardinality fields, i.e. the usable cross-filter dimensions. Values listed`);
w(`are the **complete** observed set for this corpus.`);
w();
for (const [key, s] of Object.entries(snap.shapes).sort((a, b) => b[1].count - a[1].count)) {
  const cats = Object.entries(s.paths).filter(
    ([p, v]) =>
      v.categorical && v.categorical.length > 1 && v.categorical.length <= 24 && !isNoise(p, v),
  );
  if (cats.length === 0) continue;
  w(`### \`${key}\``);
  w();
  w(`| field | presence | values |`);
  w(`| --- | ---: | --- |`);
  for (const [p, v] of cats) {
    w(`| ${code(p)} | ${pct(v.presence)} | ${v.categorical.map(code).join(" ")} |`);
  }
  w();
}

// --- tool surface ----------------------------------------------------------

w(`## Tool surface`);
w();
w(`Tool call parameters are censused separately from transcript schema — a tool`);
w(`gaining a parameter is a Claude Code feature change, not a log-format change.`);
w();
w(`| tool | calls | parameters |`);
w(`| --- | ---: | --- |`);
for (const [name, t] of Object.entries(snap.toolSchemas ?? {})) {
  const params = Object.entries(t.params)
    .map(([k, v]) => (v.presence >= 0.99 ? `**${k}**` : k))
    .join(", ");
  w(`| \`${name}\` | ${n(t.calls)} | ${params || "—"} |`);
}
w();
w(`Bold = present on every call (effectively required).`);
w();

// --- collapsed ------------------------------------------------------------

if (c.collapsedDictPaths?.length) {
  w(`## Collapsed paths`);
  w();
  w(`These are data-keyed maps, not structs; their keys collapse to \`{}\` so that`);
  w(`the user's own file names do not appear as schema fields.`);
  w();
  for (const p of c.collapsedDictPaths) w(`- ${code(p)}`);
  w();
}

console.log(out.join("\n"));

// ---------------------------------------------------------------------------

/** Drop fields whose "categories" are really just sparse free text. */
function isNoise(p, v) {
  if (/uuid|Uuid|^id$|timestamp|^cwd$|Id$/.test(p)) return true;
  return v.categorical.some((s) => s.length > 60);
}
function cmpVersion(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    if ((pa[i] ?? 0) !== (pb[i] ?? 0)) return (pa[i] ?? 0) - (pb[i] ?? 0);
  }
  return 0;
}
