/**
 * `aiui extension` — manage the aiui browser extension's native side
 * (browser-extension proposal §4). Today: install/inspect the Chrome
 * native-messaging host that lets the extension enumerate channels cold
 * (the on-disk registry is unreachable from a browser).
 *
 * `install-native-host` writes two things, both idempotent:
 *  1. A wrapper script under the user cache that execs this CLI's
 *     `native-host` subcommand with absolute paths (Chrome spawns NM hosts
 *     with a minimal environment and cwd `/` — nothing here may rely on PATH
 *     or working directory; `--import tsx` resolves from cwd, hence the `cd`).
 *  2. The NM manifest into each installed browser's user-level
 *     `NativeMessagingHosts/` directory (macOS + Linux paths; Chrome, Chrome
 *     for Testing, Chromium, Edge). `allowed_origins` pins the extension id —
 *     the default is the stable id derived from the key checked into
 *     `packages/aiui-extension/manifest.config.ts`.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { cacheDir, packageRoot } from "@habemus-papadum/aiui-util";
import { resolvePackageCli } from "../util/resolve-cli";

/** The NM host name (lowercase alphanumerics, dots, underscores only). */
export const NATIVE_HOST_NAME = "com.habemus_papadum.aiui";

/** The stable unpacked-extension id (from the pinned manifest key). */
export const DEFAULT_EXTENSION_ID = "ngakidpkjdgaajnlpggbchpaikilkpmp";

export interface ExtensionOptions {
  extensionId?: string;
}

/** Browser NM manifest directories, user-level, per platform. */
export function nativeHostManifestDirs(platform: NodeJS.Platform, home: string): string[] {
  if (platform === "darwin") {
    const base = join(home, "Library", "Application Support");
    return [
      join(base, "Google", "Chrome", "NativeMessagingHosts"),
      join(base, "Google", "ChromeForTesting", "NativeMessagingHosts"),
      join(base, "Chromium", "NativeMessagingHosts"),
      join(base, "Microsoft Edge", "NativeMessagingHosts"),
    ];
  }
  if (platform === "linux") {
    return [
      join(home, ".config", "google-chrome", "NativeMessagingHosts"),
      join(home, ".config", "google-chrome-for-testing", "NativeMessagingHosts"),
      join(home, ".config", "chromium", "NativeMessagingHosts"),
      join(home, ".config", "microsoft-edge", "NativeMessagingHosts"),
    ];
  }
  throw new Error(`aiui extension: unsupported platform ${platform} (macOS/Linux only for now)`);
}

/** The wrapper script body. Exported for tests. */
export function wrapperScript(cwd: string, command: string, args: string[]): string {
  const q = (s: string): string => `"${s.replace(/(["\\$`])/g, "\\$1")}"`;
  return [
    "#!/bin/sh",
    "# aiui native-messaging host wrapper — generated by `aiui extension install-native-host`.",
    "# Chrome spawns this with a minimal env and cwd /; everything below is absolute.",
    `cd ${q(cwd)} || exit 1`,
    `exec ${[command, ...args].map(q).join(" ")} native-host`,
    "",
  ].join("\n");
}

export function runExtension(action: string, options: ExtensionOptions = {}): void {
  if (action === "install-native-host") {
    installNativeHost(options);
    return;
  }
  if (action === "status") {
    statusNativeHost();
    return;
  }
  throw new Error(`aiui extension: unknown action "${action}" (install-native-host | status)`);
}

function wrapperPath(): string {
  return join(cacheDir("native-host", { create: true }), "aiui-native-host.sh");
}

function installNativeHost(options: ExtensionOptions): void {
  const extensionId = options.extensionId ?? DEFAULT_EXTENSION_ID;
  const cli = resolvePackageCli("@habemus-papadum/aiui");
  const root = packageRoot("@habemus-papadum/aiui");

  const wrapper = wrapperPath();
  writeFileSync(wrapper, wrapperScript(root, cli.command, cli.args));
  chmodSync(wrapper, 0o755);
  process.stdout.write(`wrote ${wrapper}\n`);

  const manifest = {
    name: NATIVE_HOST_NAME,
    description: "aiui native-messaging host: channel discovery for the aiui browser extension",
    path: wrapper,
    type: "stdio",
    allowed_origins: [`chrome-extension://${extensionId}/`],
  };
  for (const dir of nativeHostManifestDirs(process.platform, homedir())) {
    mkdirSync(dir, { recursive: true });
    const file = join(dir, `${NATIVE_HOST_NAME}.json`);
    writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);
    process.stdout.write(`wrote ${file}\n`);
  }
  process.stdout.write(
    `native host installed for extension ${extensionId}.\n` +
      "No browser restart needed; reload the extension if it was already running.\n",
  );
}

function statusNativeHost(): void {
  const wrapper = wrapperPath();
  process.stdout.write(`wrapper: ${wrapper} ${existsSync(wrapper) ? "(present)" : "(MISSING)"}\n`);
  for (const dir of nativeHostManifestDirs(process.platform, homedir())) {
    const file = join(dir, `${NATIVE_HOST_NAME}.json`);
    if (!existsSync(file)) {
      process.stdout.write(`absent:  ${file}\n`);
      continue;
    }
    try {
      const parsed = JSON.parse(readFileSync(file, "utf8")) as { allowed_origins?: string[] };
      process.stdout.write(`present: ${file} → ${parsed.allowed_origins?.join(", ")}\n`);
    } catch {
      process.stdout.write(`present: ${file} (unparseable)\n`);
    }
  }
}
